name: publish
description: "Builds MkDocs website and publish it to GitHub pages"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - shell: bash
      run: |
        pip install mkdocs mkdocs-material

    - name: Generate web site
      shell: sh
      run: |
        mkdocs build

    - name: Deploy to GH pages
      shell: sh
      run: |
        mkdocs gh-deploy --force -m "update site"
      working-directory: .
